// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxnufrtblojaqengnfby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bnVmcnRibG9qYXFlbmduZmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjI5MDUsImV4cCI6MjA1OTYzODkwNX0.jXR45XARt8bQNOLLbm3nEgY5enztRXJfpC9f4U1GfUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);